#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Sep 08 16:29:02 KST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
bin_path="/tools/questa/questasim/bin"
set -Eeuo pipefail
source tb_axis_fifo_example_compile.do 2>&1 | tee compile.log

