#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 08 15:23:20 KST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/tools/questa/questasim/bin"
set -Eeuo pipefail
$bin_path/vsim -64  -do "do {tb_axis_fifo_example_simulate.do}" -l simulate.log

