######################################################################
#
# File name : tb_axis_fifo_example_compile.do
# Created on: Mon Sep 08 15:23:19 KST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/tools/questa/questasim/bin/vlib questa_lib/work
/tools/questa/questasim/bin/vlib questa_lib/msim

/tools/questa/questasim/bin/vlib questa_lib/msim/xil_defaultlib

/tools/questa/questasim/bin/vmap xil_defaultlib questa_lib/msim/xil_defaultlib

/tools/questa/questasim/bin/vlog -64 -incr -mfcu +define+DEBUG -work xil_defaultlib  "+incdir+../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" \
"../../../../../axis_counter_src.v" \
"../../../../../axis_fifo_example_top.v" \
"../../../../../../axis_fifo_xpm.v" \
"../../../../../axis_sink_checker.v" \

/tools/questa/questasim/bin/vlog -64 -incr -mfcu -sv +define+DEBUG -work xil_defaultlib  "+incdir+../../../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" \
"../../../../../tb_axis_fifo_example.sv" \

# compile glbl module
/tools/questa/questasim/bin/vlog -work xil_defaultlib "glbl.v"

