######################################################################
#
# File name : tb_axis_fifo_example_elaborate.do
# Created on: Mon Sep 08 16:29:02 KST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/tools/questa/questasim/bin/vopt -64 -suppress 10016 +acc=blnr -debugdb +cover=sbfec -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.tb_axis_fifo_example xil_defaultlib.glbl -o tb_axis_fifo_example_opt
