######################################################################
#
# File name : tb_axis_fifo_example_simulate.do
# Created on: Mon Sep 08 15:23:20 KST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -onfinish stop  -lib xil_defaultlib tb_axis_fifo_example_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

# Enable debugging capabilities
# configure -debugdb on  # Not supported in this version

# do {tb_axis_fifo_example_wave.do}

do {wave.do}

view wave
view structure
view signals

# Load simple debug setup script (more compatible)
do {simple_debug.do}

do {tb_axis_fifo_example.udo}

run 10000ns

view wave