######################################################################
#
# File name : tb_axis_fifo_example_simulate.do
# Created on: Mon Sep 08 16:29:03 KST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -onfinish stop -lib xil_defaultlib tb_axis_fifo_example_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {wave.do}

view wave
view structure
view signals

do {tb_axis_fifo_example.udo}

run 10000ns
