######################################################################
#
# File name : tb_axis_fifo_example_elaborate.do
# Created on: Mon Sep 08 15:23:19 KST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/tools/questa/questasim/bin/vopt -64 +acc=blnr -debugdb +cover=sbfec -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.tb_axis_fifo_example xil_defaultlib.glbl -o tb_axis_fifo_example_opt
